// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {rclib} from '../models';
import {credentials} from '../models';
import {connection} from '../models';

export function AddAccount(arg1:main.LoginRequest):Promise<Array<rclib.Server>>;

export function ConnectToServer(arg1:number):Promise<void>;

export function GetServers():Promise<Array<rclib.Server>>;

export function ListAccounts():Promise<Array<credentials.AccountSummary>>;

export function LoginWithAccount(arg1:string):Promise<Array<rclib.Server>>;

export function Logout():Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function SetNewProtocol(arg1:boolean):Promise<void>;

export function Status():Promise<connection.Status>;
