// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function ConnectToServer(arg1) {
  return window['go']['main']['App']['ConnectToServer'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function LoginWithAccount(arg1) {
  return window['go']['main']['App']['LoginWithAccount'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function SetNewProtocol(arg1) {
  return window['go']['main']['App']['SetNewProtocol'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
